### ISSUE TITLE
Usable again

### ISSUE THREAD

**Issue by jputcu** [christophgysin/addp#1]
Hello

I'm currently trying to use your library but have some issues, both with compiling and running.
For example, the `lexical_cast` of ip-address and mac-address strings no longer works but throws an exception (see unittests).
To make it usable again, do you accept merge requests and questions which you can review/verify?

Kind Regards

Joris

**Comment by christophgysin** [comment]
Hi @jputcu, I'll happily accept merge requests, and will try to answer any questions you might have.
